site_name: Mini C#
site_description: Mini C# language for Spoofax
site_author: Daniel A. A. Pelsmaeker
site_dir: .docs_site/

repo_url: https://github.com/MetaBorgCube/metaborg-mini-csharp

theme:
  name: material
  language: en
  icon:
    logo: fontawesome/solid/note-sticky
    repo: fontawesome/brands/github
  palette:
    primary: green
    accent: purple
  font:
    code: JetBrains Mono
    
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      guess_lang: false
  - pymdownx.inlinehilite
  - pymdownx.keys:
      key_map:
        click: "Click"
        left-click: "Left Click"
        right-click: "Right Click"
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.saneheaders
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

plugins:
  - search
